### ISSUE TITLE
Run diffdock on time-splitPDBind in ticket mode

### ISSUE THREAD

**Issue by NiklasTR** [labdao/ganglia#43]
batch mode?

**Comment by NiklasTR** [comment]
@thetechnocrat-dev - we are running into an issue with the new settings around mounted volumes in process.py . The process now expects all data to be mounted in home/ubuntu/inputs and /root/inputs. 

Should we:
- [ ] adopt this as a convention (happy to create that standard)
- [ ] create a way to overwrite this default in the client.py

<img width="867" alt="image" src="https://user-images.githubusercontent.com/18559148/215564264-3375edc1-c246-4ae3-a841-db67a7f9815b.png">

**Comment by thetechnocrat-dev** [comment]
@NiklasTR, I think we should standardize around inputs/outputs, similar to Bacalhau.

**Comment by NiklasTR** [comment]
sounds good - I can make the change. This also means we are dropping the -v flag in client.py I guess. What do you think?

**Comment by NiklasTR** [comment]
@thetechnocrat-dev: Changing the default directory path for the inputs from /root/inputs to /inputs. AFAIK that is the default on bacalhau right now

**Comment by NiklasTR** [comment]
made the change, but still working through diffdock-related problems:

```
RDKit was unable to read the molecule.
Failed to read molecule  /inputs/PDBBind_processed/6qqw/6qqw_ligand.sdf  We are skipping it. The reason is the exception:  ('RDKit could not read the molecule ', '/inputs/PDBBind_processed/6qqw/6qqw_ligand.sdf')
Reading language model embeddings.
```

I will open a dedicated issue and merge this branch into main
