### ISSUE TITLE
create index.json from file structure

### ISSUE THREAD

**Issue by NiklasTR** [labdao/ganglia#61]

**Comment by NiklasTR** [comment]
An example call to the function is presented here:
```
plex util generate index --app="diffdock" --directory="home/ubuntu/dir"
```

when app=="diffdock":
- a .plex file is read that contains a JSON that specifies the file endings that are related to inputs for *app*. The entry for diffdock would look like this: 
````
{"app": "diffdock", 
   "inputs": {"protein_path": ".pdb"},
                   {"ligand": ".sdf"},
   "outputs": {"pdb", "sdf"}}

````
- a temporary directory *tmp* is created
- all files matching the file endings listed for *app* are listed
- all listed files are copied to *tmp* in a flat directory structure
- a jsonlines object is created that lists the files in *tmp* according to the JSON that is stored in .plex
````
{"protein_path", "ligand"}
{"protein1.pdb", "ligand1.sdf}
{"protein1.pdb", "ligand2.sdf}
````

**Comment by NiklasTR** [comment]
missing pieces as of 23-02-04:
- [ ] index.csv generation from moved files
- [ ] instruction.json generation (will require upgrade to app-config 
- [ ] additional tests
- [ ] refactoring of main for integration into plex

plex = ProtocoL EXchange

**Comment by NiklasTR** [comment]
instead of an index.csv, I decided to create a dictionary that specifies the nature of each file. From there, a .csv file can be created.

**Comment by thetechnocrat-dev** [comment]
output is creating job directory locally and index file locally

then we can create two CIDS.
