### ISSUE TITLE
run equibind on plex

### ISSUE THREAD

**Issue by acashmoney** [labdao/ganglia#72]

**Comment by NiklasTR** [comment]
* basically this is onboarding a second application.

**Comment by NiklasTR** [comment]
I am currently implementing this with 
````
while IFS=, read -r protein ligand; do main.py --protein "$protein" --small_molecule_library "$ligand"; done < /inputs/index.csv | tail -n +2   

````

my current process: 

- [ ] run on a test csv locally 
- [ ] run in a docker on a test csv
- [ ] run in equibind on a local machine
- [ ] bacalhau live test

**Comment by NiklasTR** [comment]
live test is running BUT we need to introduce a gpu flag in the app config. Will introduce that now.

**Comment by NiklasTR** [comment]
I created a hack that uses a string CLI flag "gpu" to fix this for now.
